[accounts.gmail]
default = true
email = "googlillo@gmail.com"
display-name = "googlillo"
downloads-dir = "/home/marcel/downloads"

folder.alias.inbox = "INBOX"
folder.alias.sent = "[Gmail]/Sent Mail"
folder.alias.drafts = "[Gmail]/Drafts"
folder.alias.trash = "[Gmail]/Trash"

backend.type = "imap"
backend.host = "imap.gmail.com"
backend.port = 993
backend.login = "googlillo@gmail.com"
backend.encryption.type = "tls"
backend.auth.type = "password"
backend.auth.command = "pass show gmail/googlillo/password"

message.send.backend.type = "smtp"
message.send.backend.host = "smtp.gmail.com"
message.send.backend.port = 465
message.send.backend.login = "googlillo@gmail.com"
message.send.backend.encryption.type = "tls"
message.send.backend.auth.type = "password"
message.send.backend.auth.command = "pass show gmail/googlillo/password"
