keys:
  - &nixos age16phd3r65ggmhv090r57es8ygt7j0y0tjezfndkuaptgmk50rxyms56ys87
  - &work age1yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy     # Add work host's public key here

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *nixos
          - *work