$mainMod = Alt # Sets "Windows" key as main modifier

bind = $mainMod, TAB, exec, ~/scripts/hyprland/toggle-lock-window.sh
windowrule = border_color rgb(FFFFFF), match:fullscreen 1
windowrule = border_color rgba(F6D86Aff), match:tag locked
