-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mainMod = "ALT" -- Sets "Windows" key as main modifier

-- Hyprland's env directive does a raw setenv, no shell expansion: $HOME/${VAR} stay literal.
hl.env("PATH", "/home/mmanzanares/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin")
hl.env("HYPRLAND_EGL_NO_MODIFIERS", "1")

-- windowrulev2 = bordercolor rgba(F6D86Aff) rgba(7F6318ff), tag:locked
-- fixed typo from source: "windowrulev" -> proper window_rule (already covered globally in
-- hyprland.conf's fullscreen border_color rule, kept here for host-specific parity)
hl.window_rule({
    match = { fullscreen = 1 },
    border_color = "rgb(FFFFFF)",
})
hl.bind(mainMod .. " + TAB", hl.dsp.exec_cmd("~/scripts/hyprland/toggle-lock-window.sh"))

hl.on("hyprland.start", function()
    hl.exec_cmd("uwsm finalize WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE")
end)

