# vim: set ft=toml:

# More info at: ./foot.ini.template
# or https://codeberg.org/dnkl/foot/src/branch/master/foot.ini

# shell=fish
# shell=bash
# shell=/usr/bin/nu # This creates issues

# font=JetBrainsMono Nerd Font:size=10


[cursor]
style=block
# color=4b4b46 020221

[colors-dark]
background=151515

[colors-light]
background=f0f0f0
foreground=202020

[main]
initial-color-theme=dark
pad=15x10 center
font=Myna:size=10
# multi-extraction=true # still in development
# font=BlexMono Nerd Font:size=10
# font=Px437 NEC APC3 8x16:size=10
# font=AcPlus ToshibaSat 8x14:size=12
# font=Iosevka Term Nerd Font Mono:size=11

[scrollback]
indicator-position=none
# search-mode=regex

[regex:hashes]
regex=([a-fA-f0-9]{7,128})
launch= ${match}

[regex:paths]
regex=(\./[^ ]+|\.\./[^ ]+|/[^ ]+|~/[^ ]+)
launch=${match}

[regex:urls]
regex=([A-Za-z][A-Za-z0-9+.-]*://[^[:space:]]+)
launch=${match}


[key-bindings]
regex-copy=[paths] Control+Shift+p
regex-copy=[urls] Control+Shift+y
show-urls-launch=Control+Shift+o

# [cursor]
# style=underline
