-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- source = ~/.config/hypr/myColors.conf

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mainMod = "ALT" -- Sets "Windows" key as main modifier (unused, kept for parity with source)

-- env = WLR_RENDERER,vulkan # this fix did not work
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
-- ponytail: compositor scale (kanshi, per-output) sizes everything; no global Qt/GDK scaling.
-- QT_SCALE_FACTOR/GDK_SCALE also hit Wayland-native Qt (Dolphin, jellyfin-desktop) -> ~2x too big,
-- and were wrong on scale-1/2.5 monitors. Wayland-native apps use the compositor scale natively.

-- Create symlink to hostname-specific config (devices/nixos.lua, devices/work-laptop.lua, etc)
require("device")

-- unsure about this 
-- env = XDG_DATA_DIRS,$HOME/.nix-profile/share:/nix/var/nix/profiles/default/share:/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("EDITOR", "nvim")
hl.env("VISUAL", "nvim")
hl.env("SUDO_EDITOR", "nvim")
hl.env("TERMINAL", "foot")
-- env = XCURSOR_THEME,Retrosmart
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("MOZ_DPI_ADJUST", "0.9")
hl.env("XCURSOR_THEME", "retrosmart-xcursor-white")
hl.env("XCURSOR_SIZE", "16")
hl.env("HYPRCURSOR_THEME", "retrosmart-xcursor-white")
hl.env("HYPRCURSOR_SIZE", "16")
-- env = WLR_DRM_NO_MODIFIERS,1

-- ponytail: force_zero_scaling renders XWayland at 1:1 (sharp) instead of compositor-upscaled (blurry on fractional 1.67).
-- Cost: XWayland apps appear small until they self-scale. Bitwig: Settings > Appearance ~170-200%. Wayland-native apps unaffected.

hl.workspace_rule({
    workspace = "0",
    default_name = "scratch",
})

hl.workspace_rule({
    workspace = "1",
    default_name = "browse",
})

hl.workspace_rule({
    workspace = "2",
    default_name = "code",
})

hl.workspace_rule({
    workspace = "3",
    default_name = "learn",
})

local terminal = "alacritty -e fish"
local fileManager = "nemo"
local menu = "tofi-drun"

hl.env("XCURSOR_SIZE", "16")
hl.env("HYPRCURSOR_SIZE", "16")

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 7,
    bezier = "myBezier",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 7,
    bezier = "default",
    style = "popin 80%",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 8,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 7,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 6,
    bezier = "default",
})

hl.device({
    name = "synps/2-synaptics-touchpad",
    sensitivity = 0.5,
    natural_scroll = false,
    tap_to_click = true,
    tap_and_drag = true,
    clickfinger_behavior = false,
    middle_button_emulation = true,
})

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

require("keybinds")

hl.window_rule({
    match = {
        class = "eww-bar",
    },
    pin = true,
    stay_focused = true,
})

hl.window_rule({
    match = {
        title = "Volume Control",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "Bluetooth",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "Customize Look and Feel",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "Welcome",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "Smile",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "OpenGL Renderer",
    },
    float = true,
    pin = true,
})

hl.window_rule({
    match = {
        title = "satty",
    },
    fullscreen = true,
})

hl.window_rule({
    match = {
        workspace = "special:whats",
    },
    float = true,
    center = true,
})

hl.bind("SUPER + SPACE", hl.dsp.exec_cmd("hyprctl switchxkblayout all next"))

hl.window_rule({
    match = {
        class = "imv",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "swayimg",
    },
    fullscreen = true,
})

hl.window_rule({
    match = {
        title = "^(Audio Select)$",
    },
    float = true,
    size = "300 400",
})

hl.window_rule({
    match = {
        title = "^(Calendar Reminders)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Volume Control)$",
    },
    float = true,
    size = "1000 500",
})

hl.window_rule({
    match = {
        fullscreen = 1,
    },
    border_color = "rgb(FFFFFF)",
})

hl.window_rule({
    match = {
        tag = "locked",
    },
    border_color = "rgba(ff79c6ff)",
})

hl.window_rule({
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
    --###############
    --## MONITORS ###
    --###############
    -- source = ~/.config/hypr/monitors.conf
    -- exec = kanshi ~/.config/kanshi/config
    -- See https://wiki.hyprland.org/Configuring/Monitors/
    -- monitor=,highres,auto,auto
    -- monitor=eDP-1,3840x2160@60,0x0,2.5
    -- Mirror screens
    -- monitor=HDMI-A-1,3840x2160@60,0x0,1, mirror, DP-2
    -- monitor=HDMI-A-1,1920x1080@60,0x0,1, mirror, DP-2
    -- monitor=DP-2,3840x2160@60,0x0,1, mirror, HDMI-A-1
    --##################
    --## MY PROGRAMS ###
    --##################
    -- See https://wiki.hyprland.org/Configuring/Keywords/
    -- Set programs that you use
    -- $menu = pkill wofi || wofi --show drun
    -- $menu = ulauncher
    --################
    --## AUTOSTART ###
    --################
    -- Autostart necessary processes (like notifications daemons, status bars, etc.)
    -- Or execute your favorite apps at launch like this:
    -- exec-once = $terminal
    -- exec-once = ~/.config/eww/scripts/monitor.sh
    -- exec = ~/.config/eww/scripts/start.sh
    -- exec-once = eww deamon
    -- exec-once = ~/.config/eww/launch.sh
    -- exec-once = pypr --debug /tmp/pypr.log
    -- exec-once = hyprpaper &
    -- exec-once = swaybg --image ~/img/dark-grey.png --mode fill &
    -- exec-once = mako
    -- exec = kanshictl reload
    -- UI scaling for sharp rendering at scale 2
    -- Clipse 
    -- exec-once = clipse -listen # run listener on startup
    -- windowrule = float,class:(clipse) # ensure you have a floating window class set if you want this behavior
    -- windowrule = size 622 652,class:(clipse) # set the size of the window as necessary
    -- bind = SUPER, C, exec, foot -a clipse -L clipse
    --############################
    --## ENVIRONMENT VARIABLES ###
    --############################
    -- See https://wiki.hyprland.org/Configuring/Environment-variables/
    --####################
    --## LOOK AND FEEL ###
    --####################
    -- Refer to https://wiki.hyprland.org/Configuring/Variables/
    -- https://wiki.hyprland.org/Configuring/Variables/#general
    general = {
        gaps_in = 5,
        gaps_out = 5,
        border_size = 1,
        -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
        -- https://wiki.hypr.land/Configuring/Basics/Variables/
        col = {
            active_border = "rgb(007f86)",
            inactive_border = "rgba(64666c55)",
        },
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = true,
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#decoration
    decoration = {
        rounding = 0,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = false,
        },
        -- https://wiki.hyprland.org/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#animations
    animations = {
        enabled = false,
        -- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    },
    -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    dwindle = {
        preserve_split = true, -- You probably want this
        force_split = 2,
    },
    -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    master = {
        orientation = "right",
        -- new_status = master
        new_on_top = true,
        -- new_is_master = true
        allow_small_split = true,
        -- new_on_top = false
        -- new_on_active = after
        -- no_gaps_when_only = -2
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#misc
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
    },
    cursor = {
        inactive_timeout = 3,
    },
    --############
    --## INPUT ###
    --############
    -- https://wiki.hyprland.org/Configuring/Variables/#input
    input = {
        kb_layout = "us,es",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        repeat_rate = 55,
        repeat_delay = 300,
        follow_mouse = 0,
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = false,
            tap_to_click = true,
            tap_and_drag = true,
            drag_lock = false,
            clickfinger_behavior = false,
            middle_button_emulation = true,
            disable_while_typing = true,
        },
    },
    -- Synaptics touchpad configuration for SynPS/2
    -- https://wiki.hyprland.org/Configuring/Variables/#gestures
    gestures = {
        -- workspace_swipe = false
    },
    -- Example per-device config
    -- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
    binds = {
        workspace_back_and_forth = true,
        allow_workspace_cycles = true,
        pass_mouse_when_bound = false,
    },
    -- KEYBINDINGSS
    -- eww bar
    -- Special workspaces
    -- WhatsApp For Linux
    -- workspace = special:whats, on-created-empty:[float; move 12.5% 12.5%; size 75% 75%] wasistlos %u,class:wasistlos wasistlos
    -- bind = $mainMod SHIFT, W, exec, hyprctl dispatch togglespecialworkspace whats
    -- WhatsApp (Zap Zap) 
    -- workspace = special:whats, on-created-empty:[float; move 12.5% 12.5%; size 75% 75%] zapzap %u,class:zapzap zapzap
    -- bind = $mainMod SHIFT, W, exec, hyprctl dispatch togglespecialworkspace whats
    -- WhatsApp (Zap Zap flatpak)
    -- workspace = special:whats, on-created-empty:[float; move 12.5% 12.5%; size 75% 75%] flatpak run --socket=wayland com.rtosta.zapzap %u,class:zapzap zapzap
    -- bind = $mainMod SHIFT, W, exec, hyprctl dispatch togglespecialworkspace whats
    -- workspace = special:whats, on-created-empty:[move 12.5% 12.5%; size 75% 75%] flatpak run --socket=wayland com.rtosta.zapzap %u,class:zapzap zapzap
    -- bind = $mainMod SHIFT, W, exec, hyprctl dispatch togglespecialworkspace whats
    -- workspace = special:nnn, on-created-empty:[float; move 12.5% 12.5%; size 75% 75%] foot -e nnn %u,class:nnn nnn
    -- bind = $mainMod SHIFT, M, exec, hyprctl dispatch togglespecialworkspace nnn
    -- Keyboard layout switch
    -- workspace = special:webcam, on-created-empty:[float; move 12.5% 12.5%; size 50% 50%] /home/marcel/scripts/show_webcam.sh
    -- bind = $mainMod, W, exec, hyprctl dispatch togglespecialworkspace webcam
    --
    -- windowrule = workspace special:webcam, title:gst-launch-1.0
    -- windowrule = float, workspace:special:webcam
    -- windowrule = pin, workspace:special:webcam
    -- Foot term
    -- workspace = special:term, on-created-empty:[float; move 25% 25%; size 50% 50%] foot -a nu -L nu
    -- bind = SUPER, S, exec, hyprctl dispatch togglespecialworkspace term
    -- Flameshot
    -- windowrule = size 3840 1200, flameshot
    -- windowrule = suppressevent fullscreen, class:(flameshot), title:(flameshot)
    -- windowrule = rounding 0, class:(flameshot), title:(flameshot)
    -- windowrule = noborder, class:(flameshot), title:(flameshot)
    -- windowrule = monitor DP-5, class:(flameshot), title:(flameshot)
    -- windowrule = monitor DP-6, class:(flameshot), title:(flameshot)
    -- windowrule = fullscreenstate, class:(flameshot), title:(flameshot)
    -- windowrule = move 0 0, class:(flameshot), title:(flameshot)
    -- windowrule = stayfocused, class:(flameshot), title:(flameshot)
    -- windowrule = size 3840 1200, class:(flameshot), title:(flameshot)
    -- windowrule = float, class:(flameshot), title:(Upload image)
    -- windowrule = float, class:(flameshot), title:(Configuration)
    -- windowrule = float, class:(flameshot), title:(Capture Launcher)
    -- windowrule = float, class:(flameshot), title:(Save screenshot)
    --#############################
    --## WINDOWS AND WORKSPACES ###
    --#############################
    -- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
    -- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
    -- Example windowrule v1
    -- windowrule = float, ^(kitty)$
    -- Example windowrule v2
    -- windowrule = float,class:^(kitty)$,title:^(kitty)$
    debug = {
        disable_logs = false,
    },
    -- Test comment
    -- source = ./dms/cursor.conf
    -- source = ./dms/outputs.conf
})

hl.on("hyprland.start", function()
    hl.exec_cmd("ln -sf ~/.config/hypr/devices/$(hostname).lua ~/.config/hypr/device.lua")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("swayosd-server &")
    hl.exec_cmd("nm-applet --indicator &")
    hl.exec_cmd("blueman-applet &")
    hl.exec_cmd("batsignal -b -w 20 -c 7 -d 5")
    hl.exec_cmd("ydotool &")
    hl.exec_cmd("pypr")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("kanshi")
    hl.exec_cmd("sh -c \"mkfifo $XDG_RUNTIME_DIR/wob-volume.sock 2>/dev/null; tail -f $XDG_RUNTIME_DIR/wob-volume.sock | wob -c ~/.config/wob/wob-volume.ini\"")
    hl.exec_cmd("sh -c \"mkfifo $XDG_RUNTIME_DIR/wob-brightness.sock 2>/dev/null; tail -f $XDG_RUNTIME_DIR/wob-brightness.sock | wob -c ~/.config/wob/wob-brightness.ini\"")
end)

hl.on("config.reloaded", function()
    hl.exec_cmd("pkill waybar; waybar &")
    hl.exec_cmd("~/scripts/waybar/dark-light-toggle.sh")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-size 24")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface text-scaling-factor 0.9")
end)

