-- vi: ft=hyprlang
--###################
--## KEYBINDINGSS ###
--###################

-- See https://wiki.hyprland.org/Configuring/Keywords/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local menu = "tofi-drun"
local mainMod = "ALT" -- Sets "Windows" key as main modifier
local altMod = "SUPER" -- Sets "Windows" key as main modifier
local browser = "brave-origin-nightly"

-- $mainMod = SUPER

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
-- bind = $mainMod, Return, exec, ~/scripts/hyprland/toggle-fullscreen.sh 'alacritty -e fish'
-- bind = $mainMod, Return, exec, ~/scripts/hyprland/toggle-fullscreen.sh 'foot -e nu'
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd("'foot'"))
hl.workspace_rule({
    workspace = "special:scratchpad",
    on_created_empty = "foot",
})

hl.bind(mainMod .. " + n", hl.dsp.workspace.toggle_special("magic"))
-- bind = $mainMod, e, exec, ~/.config/eww/toggle-bar.sh
hl.bind(mainMod .. " + e", hl.dsp.exec_cmd("pkill -USR1 waybar"))
-- bind = $mainMod SHIFT, m, exec, ~/scripts/wl-mirror-menu.sh
-- bind = $mainMod SHIFT, P, exec, ~/scripts/pdf-selector.sh
-- bind = $mainMod SHIFT, P, exec, passmenu -i
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd("~/scripts/rbwmenu"))

-- video-selector moved from M to T (M now = Matrix/Cinny). T ~ TV/video.
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("~/scripts/video-selector.sh"))
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("~/scripts/video-selector.sh --dirs"))
-- bind = $mainMod SHIFT, # bind = $mainMod SHIFT, S, movetoworkspace, special:magic
-- bind = $mainMod SHIFT, n, exec, [workspace special term; float; move 25% 25%; size 50% 50%] foot

-- bind = $mainMod, Return, exec, $terminal
-- bind = $mainMod SHIFT, Q, killactive,
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exec_cmd("~/scripts/hyprland/safe-killactive.sh"))
-- bind = $mainMod, M, exit,
-- bind = $mainMod, M, exec, $fileManager
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(browser .. " --container=\"Work\" \"https://kagi.com\""))
hl.bind(mainMod .. " + O", hl.dsp.exec_cmd(browser .. " --container=\"Personal\" \"https://kagi.com\""))
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd("wofi-emoji"))
hl.bind(mainMod .. " + Z", hl.dsp.exec_cmd("pypr zoom ++0.5"))
-- WhatsApp via Cinny desktop — Tauri build has no URL deep-link scheme, so this
-- just launches the app at its last room (not the WA room specifically).
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("pypr toggle cinny"))
hl.bind(mainMod .. " + SHIFT + I", hl.dsp.exec_cmd("pypr shift_monitors +1"))
hl.bind(mainMod .. " + SHIFT + Z", hl.dsp.exec_cmd("hyprctl reload && pypr zoom"))
-- bind = $mainMod SHIFT, N, exec, foot --title "nnn-term" -e nnn
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.exec_cmd("swaync-client -t"))
hl.window_rule({
    match = {
        title = "^(nnn-term)$",
    },
    float = true,
})

-- bind = $mainMod SHIFT, W, exec, pypr toggle whats
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("pypr toggle volume"))

-- disable for digital detox
-- bind = $mainMod SHIFT, W, exec, whatsie
-- bind = $mainMod SHIFT, W, exec, flatpak run com.rtosta.zapzap 

-- $browser kiosk programs
hl.bind(mainMod .. " + SHIFT + O", hl.dsp.exec_cmd(browser .. " https://ai.marcel.cool"))
-- bind = $mainMod SHIFT, G, exec, $browser https://gemini.google.com/u/1/app
-- bind = $mainMod SHIFT, G, exec, $browser "ext+container:name=Work&url=https://gemini.google.com/u/1/app"
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd(browser .. " --container=\"Work\" \"https://gemini.google.com/u/1/app\""))
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.exec_cmd(browser .. " https://excalidraw.com"))

-- $browser kiosk-like but not compositor fullscreen
-- windowrule = match:class $browser, float
-- windowrule = match:class $browser, size 1280 800
-- windowrule = match:class $browser, move 320 140
-- windowrule = match:class $browser, fullscreenstate:0 0

-- bind = $mainMod SHIFT, G, exec, viagee
hl.bind(mainMod .. " + V", function()
    hl.dispatch(hl.dsp.window.float({ action = "toggle" }))
    hl.dispatch(hl.dsp.window.center())
end)
-- bind = $mainMod, V, resizeactive, exact 800 500
-- bind = $mainMod, V, moveactive, exact 370 150
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("~/scripts/script-selector.sh --tofi"))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("pkill tofi || cliphist list | tofi --fuzzy-match=true | cliphist decode | wl-copy"))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(menu))
-- bind = $mainMod SHIFT, D, exec, dmenu-wl_run -m $(hyprctl -j monitors | jq '.[] | select(.focused==true) | .id')
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd("~/scripts/tofi/power-selector.sh"))
-- bind = $mainMod, P, pseudo, # dwindle

-- bind = $mainMod, F, exec, hyprctl dispatch fullscreen 1 && hyprctl dispatch submap fs
--
-- submap = fs
-- bind = $mainMod, J, cyclenext
-- bind = $mainMod, K, cyclenext, prev
-- bind = $mainMod, F, exec, hyprctl dispatch fullscreen 1 && hyprctl dispatch submap reset
-- bind = , escape, submap, reset
-- submap = reset

hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
-- bind = $mainMod, E, togglesplit, # dwindle
-- bind = $mainMod, E, layoutmsg, orientationcycle # master
-- bind = $mainMod,  PRINT, exec, $HOME/scripts/hyprland/region-screenshot.sh
hl.bind(mainMod .. " + PRINT", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | swappy -f -"))
-- bind = $mainMod, PRINT, exec,  $HOME/scripts/hyprland/native-scale-screenshot.sh
-- bind = $mainMod, PRINT, exec, hyprshot -m region -m active 
-- bind = $mainMod, PRINT, exec, hyprshot -m region 
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("$HOME/scripts/hyprland/qr-code-reader.sh"))
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("$HOME/scripts/hyprland/screenshot-text-extractor.sh"))
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload && pypr reload && swaync-client --reload-css"))
hl.bind(mainMod .. " + SHIFT + X", hl.dsp.exec_cmd("hyprctl kill"))
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("pypr toggle term"))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "d" }))

hl.bind(mainMod .. " + E", hl.dsp.layout("orientationnext"))

hl.bind("ALT + R", hl.dsp.submap("resize"))
-- will start a submap called "resize"
hl.define_submap("resize", function()
    hl.bind("l", hl.dsp.window.resize({ x = 50, y = 0, relative = true }))
    hl.bind("h", hl.dsp.window.resize({ x = -50, y = 0, relative = true }))
    hl.bind("k", hl.dsp.window.resize({ x = 0, y = -50, relative = true }))
    hl.bind("j", hl.dsp.window.resize({ x = 0, y = 50, relative = true }))
    -- use reset to go back to the global submap
    hl.bind("escape", hl.dsp.submap("reset"))
    -- will reset the submap, meaning end the current one and return to the global one
end)

hl.bind(altMod .. " + l", hl.dsp.window.resize({ x = 50, y = 0, relative = true }))
hl.bind(altMod .. " + h", hl.dsp.window.resize({ x = -50, y = 0, relative = true }))
hl.bind(altMod .. " + k", hl.dsp.window.resize({ x = 0, y = -50, relative = true }))
hl.bind(altMod .. " + j", hl.dsp.window.resize({ x = 0, y = 50, relative = true }))

-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

-- bind = $mainMod, o, exec, $HOME/scripts/hyprland/reorder-workspaces.sh

-- F keys
-- bind = F1, , exec, foot

-- Example special workspace (scratchpad)
-- bind = $mainMod, S, togglespecialworkspace, magic
-- bind = $mainMod SHIFT, S, movetoworkspace, special:magic

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("$HOME/scripts/bluetooth-selector.sh"))
-- bind = $mainMod SHIFT, W, exec, $HOME/scripts/show_webcam.sh

-- Lock on lid open
hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd("hyprlock --immediate"), { locked = true })
-- Lock lid on close
hl.bind("switch:off:Lid Switch", hl.dsp.exec_cmd("hyprlock --immediate"), { locked = true })

-- Simple volume keybinds
-- binde = , XF86AudioLowerVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 10%-
-- binde = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 10%+ 
-- binde = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

-- SwayOSD volume keybinds
-- binde = , XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise
-- binde = , XF86AudioLowerVolume, exec, exec  swayosd-client --output-volume lower
-- binde = , XF86AudioMute, exec, swayosd-client --output-volume mute-toggle
-- binde = , XF86AudioMicMute, exec, swayosd-client --input-volume mute-toggle

-- Pulseaudio volume keybinds
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("$HOME/scripts/volume-control.sh up"), { repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("$HOME/scripts/volume-control.sh down"), { repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pamixer -t && ([ \"$(pamixer --get-mute)\" = \"true\" ] && echo 0 > $XDG_RUNTIME_DIR/wob-volume.sock || pamixer --get-volume > $XDG_RUNTIME_DIR/wob-volume.sock) && pkill -RTMIN+11 waybar"), { repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("pactl set-source-mute @DEFAULT_SOURCE@ toggle && pkill -RTMIN+11 waybar"), { repeating = true })

hl.bind(mainMod .. " + TAB", hl.dsp.exec_cmd("~/scripts/hyprland/toggle-lock-window.sh"))

-- Pipewire/Wireplumber volume keybinds
-- binde = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.25 @DEFAULT_AUDIO_SINK@ 5%+
-- binde = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
-- binde = , XF86AudioMute,        exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
-- binde = , XF86AudioMicMute,     exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

-- brightnessctl keybinds
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 5%- && brightnessctl -m | cut -d, -f4 | tr -d '%' > $XDG_RUNTIME_DIR/wob-brightness.sock"), { repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s +5% && brightnessctl -m | cut -d, -f4 | tr -d '%' > $XDG_RUNTIME_DIR/wob-brightness.sock"), { repeating = true })
