[colors-light]
# Alabaster (Nikita Prokopov) - minimal, near-monochrome
background=f7f7f7
foreground=000000

regular0=000000
regular1=aa3731
regular2=448c27
regular3=cb9000
regular4=325cc0
regular5=7a3e9d
regular6=0083b2
regular7=f7f7f7

bright0=777777
bright1=f05050
bright2=60cb00
bright3=e0b400
bright4=007acc
bright5=e64ce6
bright6=00aacb
bright7=ffffff
