[colors.primary]
background = "0x151515"
foreground = "#CECECE"

[colors.cursor]
text = "#0E1415"
cursor = "#CECECE"

[colors.selection]
background = "#DDF0FF"
text = "#CECECE"

[colors.normal]
black   = "#000000"
red     = "#E25D56"
green   = "#73CA50"
yellow  = "#E9BF57"
blue    = "#4A88E4"
magenta = "#915CAF"
cyan    = "#23ACDD"
white   = "#CECECE"

[colors.bright]
black   = "#777777"
red     = "#F36868"
green   = "#88DB3F"
yellow  = "#F0BF7A"
blue    = "#6F8FDB"
magenta = "#E987E9"
cyan    = "#4AC9E2"
white   = "#FFFFFF"

