[colors.primary]
background = '#000000'
foreground = '#e6f0ff'

[colors.selection]
text = '#e6f0ff'
background = '#cc5200'

[colors.cursor]
text = '#000000'
cursor = '#ffffff'

[colors.normal]
black   = '#000000'
red     = '#cc3375'
green   = '#9dd66e'
yellow  = '#dba87b'
blue    = '#bc4b4b'
magenta = '#bfbfbf'
cyan    = '#FFFFFF'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f97'
green   = '#aee086'
yellow  = '#e8bd97'
blue    = '#d4d4d4'
magenta = '#993d4d'
cyan    = '#8d4f46'
white   = '#ffffff'
